import { Conversation, Prompt, Assistant, FileItem, Message, UserSettings } from "@/lib/types";

export const DEFAULT_SETTINGS: UserSettings = {
  theme: "dark",
  defaultModelId: "gemini-3.1-pro",
  enterToSend: true,
  streamingSpeed: "natural",
  soundEffects: false,
  showDisclaimer: true,
  autoSaveHistory: true,
  systemPromptPreset: "You are an intelligent, thoughtful, and precise AI assistant.",
  temperature: 0.7,
};

export const INITIAL_CONVERSATIONS: Conversation[] = [];

export const INITIAL_MESSAGES: Record<string, Message[]> = {};

export const INITIAL_PROMPTS: Prompt[] = [
  {
    id: "prompt-1",
    title: "Senior Full-Stack Code Reviewer",
    description: "ตรวจสอบโค้ดอย่างละเอียด ทั้งด้านความปลอดภัย ประสิทธิภาพ และ Clean Architecture",
    category: "Coding",
    tags: ["React", "TypeScript", "Next.js", "Clean Code"],
    content: "กรุณารีวิวโค้ดชุดนี้ในฐานะ Senior Staff Engineer โดยวิเคราะห์:\n1. ความถูกต้องและ Edge Cases\n2. Performance & Memory Leaks\n3. Security Vulnerabilities\n4. คำแนะนำในการ Refactor ให้ Clean ยิ่งขึ้น",
    isFavorite: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prompt-2",
    title: "B2B SaaS Go-to-Market Strategy",
    description: "วางกลยุทธ์เปิดตัวผลิตภัณฑ์ วางตำแหน่งทางการตลาด และ Growth Tactics",
    category: "Business",
    tags: ["SaaS", "GTM", "Marketing", "Strategy"],
    content: "ทำหน้าที่เป็น Chief Marketing Officer (CMO) ช่วยวางแผนกลยุทธ์ Go-to-Market (GTM) สำหรับผลิตภัณฑ์ SaaS ใหม่ โดยครอบคลุม Value Proposition, ICP, ช่องทาง Acquisition และ Key Metrics ในช่วง 90 วันแรก",
    isFavorite: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prompt-3",
    title: "High-Converting Landing Page Copy",
    description: "เขียนคำพาดหัว (Headline) เนื้อหา และ Call to Action ที่จูงใจผู้อ่าน",
    category: "Marketing",
    tags: ["Copywriting", "CRO", "Landing Page"],
    content: "เขียน Copy สำหรับหน้า Landing Page ของบริการ โดยใช้กรอบ AIDA (Attention, Interest, Desire, Action) ประกอบด้วย Hero Headline, Sub-headline, 3 Key Benefits, Social Proof section และ CTA Buttons",
    isFavorite: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prompt-4",
    title: "Deep Academic Paper Summary",
    description: "สรุปเปเปอร์วิจัยเชิงวิชาการให้เข้าใจง่าย พร้อมตาราง Key Findings",
    category: "Research",
    tags: ["Academic", "Summary", "Paper", "Analysis"],
    content: "กรุณาสรุปบทความวิจัยนี้โดยแบ่งเป็น: 1. Core Problem & Hypothesis 2. Methodology & Dataset 3. Key Findings & Breakthroughs 4. Limitations และ 5. Potential Future Work ในรูปแบบตารางและสรุปใจความสำคัญ",
    isFavorite: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prompt-5",
    title: "UI/UX Design System Specification",
    description: "กำหนด Design Tokens, Color Palettes, Typography scale และ Accessibility guidelines",
    category: "Design",
    tags: ["Design System", "Tokens", "UI/UX", "Tailwind"],
    content: "สร้างสเปกสำหรับ Modern Design System โดยระบุ Design Tokens (Spacing, Colors, Radius, Typography) ที่รองรับ Dark Mode และผ่านเกณฑ์ WCAG AAA Contrast",
    isFavorite: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prompt-6",
    title: "Daily Executive Task Prioritizer",
    description: "จัดลำดับความสำคัญงานตาม Eisenhower Matrix และ Time Boxing",
    category: "Productivity",
    tags: ["Productivity", "Eisenhower", "Time Management"],
    content: "นี่คือรายการงานของฉันในวันนี้ ช่วยจัดลำดับความสำคัญตาม Eisenhower Matrix (ด่วน+สำคัญ, สำคัญ+ไม่ด่วน) พร้อมแบ่งตารางเวลาแบบ Time-Boxing ให้มีสมาธิสูงสุด",
    isFavorite: false,
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_ASSISTANTS: Assistant[] = [
  {
    id: "asst-general",
    name: "ผู้ช่วยอัจฉริยะทั่วไป",
    avatar: "🤖",
    tagline: "ผู้ช่วยรอบด้าน ตอบคำถาม ค้นคว้า และคิดวิเคราะห์",
    description: "ผู้ช่วยอัจฉริยะสารพัดประโยชน์ ตอบคำถามทั่วไป ช่วยคิดงาน และแก้ปัญหาประจำวันได้อย่างแม่นยำและสุภาพ",
    systemPrompt: "คุณคือผู้ช่วย AI อัจฉริยะระดับสูง ตอบคำถามด้วยความชัดเจน มีโครงสร้าง เข้าใจง่าย และใช้ภาษาไทยอย่างเป็นธรรมชาติและสุภาพ",
    modelId: "gemini-3.1-pro",
    temperature: 0.7,
    tools: ["Web Search", "Calculator", "Code Interpreter"],
    isPinned: true,
    isBuiltIn: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "asst-dev",
    name: "DevArchitect AI",
    avatar: "💻",
    tagline: "ผู้เชี่ยวชาญสถาปัตยกรรมระบบ โค้ด และ DevOps",
    description: "ออกแบบระบบ ซอฟต์แวร์ อัลกอริทึม รีวิวโค้ด และแก้ปัญหาบั๊กเชิงลึกสำหรับโปรแกรมเมอร์",
    systemPrompt: "คุณคือ Senior Principal Software Architect และ Full-Stack Lead ให้คำแนะนำเรื่อง Clean Code, Microservices, TypeScript, Next.js, Cloud Architecture และ DevOps อย่างมืออาชีพพร้อมตัวอย่างโค้ดที่ถูกต้อง",
    modelId: "claude-3.7-sonnet",
    temperature: 0.3,
    tools: ["Code Sandbox", "Git Analysis", "Terminal Emulator"],
    isPinned: true,
    isBuiltIn: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "asst-presscraft",
    name: "PressCraft Copywriter",
    avatar: "✍️",
    tagline: "นักเขียนคอนเทนต์ การตลาด และ Storytelling มืออาชีพ",
    description: "สร้างสรรค์บทความ คอนเทนต์โซเชียลมีเดีย สคริปต์ และคำโฆษณาที่ตรึงใจผู้อ่าน",
    systemPrompt: "คุณคือ Content Strategist และ Creative Copywriter ระดับรางวัล ช่วยเขียนและปรับแต่งเนื้อหาให้น่าอ่าน ตรงกลุ่มเป้าหมาย มีจังหวะวรรคตอนที่น่าติดตาม และสร้าง Conversion สูง",
    modelId: "gpt-5.6-terra",
    temperature: 0.85,
    tools: ["SEO Optimizer", "Tone Checker", "Headline Generator"],
    isPinned: true,
    isBuiltIn: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "asst-strategy",
    name: "Business Strategy Consultant",
    avatar: "📊",
    tagline: "ที่ปรึกษากลยุทธ์ธุรกิจ การเงิน และการเติบโต",
    description: "วิเคราะห์ตลาด วางแผนการเงิน โมเดลธุรกิจ และกลยุทธ์การขยายขนาดองค์กร",
    systemPrompt: "คุณคือ Senior Partner จาก McKinsey & Company ให้คำปรึกษาการวางแผนธุรกิจ การประเมินความเสี่ยง การวิเคราะห์คู่แข่ง และการวางโมเดลทางการเงินด้วยข้อมูลที่รอบด้าน",
    modelId: "claude-3.5-opus",
    temperature: 0.5,
    tools: ["Financial Modeling", "Competitor Matrix", "Market Insights"],
    isPinned: false,
    isBuiltIn: true,
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_FILES: FileItem[] = [
  {
    id: "file-1",
    name: "AI_Architecture_Specification_v3.pdf",
    type: "pdf",
    mimeType: "application/pdf",
    size: 2450000,
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    url: "#",
    tags: ["Architecture", "Specs", "Production"],
  },
  {
    id: "file-2",
    name: "Market_Research_Report_2026.docx",
    type: "document",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: 1180000,
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    url: "#",
    tags: ["Business", "Research", "Strategy"],
  },
  {
    id: "file-3",
    name: "Nexus_Dashboard_Wireframe.png",
    type: "image",
    mimeType: "image/png",
    size: 3820000,
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    url: "#",
    previewUrl: "/brand/wireframe-preview.png",
    tags: ["Design", "UI/UX", "Assets"],
  },
];
