import { Model, ModelCategory } from "@/lib/types";

export interface CategoryTab {
  id: ModelCategory;
  label: string;
  iconName?: string;
}

export const MODEL_CATEGORIES: CategoryTab[] = [
  { id: "recommended", label: "แนะนำ", iconName: "Sparkles" },
  { id: "all", label: "ไม่จำกัด" },
  { id: "chat", label: "สนทนา", iconName: "MessageSquare" },
  { id: "research", label: "ค้นคว้าเชิงลึก", iconName: "Telescope" },
  { id: "image", label: "สร้างรูปภาพ", iconName: "Image" },
  { id: "video", label: "สร้างวิดีโอ", iconName: "Clapperboard" },
  { id: "music", label: "สร้างเพลง", iconName: "Music" },
  { id: "google", label: "Google", iconName: "Sparkles" },
  { id: "anthropic", label: "Anthropic" },
  { id: "openai", label: "OpenAI" },
  { id: "deepseek", label: "DeepSeek", iconName: "Sparkles" },
];

export const AVAILABLE_MODELS: Model[] = [
  {
    id: "gemini-3.1-flash-lite",
    name: "Gemini 3.1 Flash Lite",
    provider: "Google",
    iconUrl: "https://i.redd.it/zl9bvu94ui3f1.png",
    description: "เหมาะสำหรับ:การตอบกลับที่รวดเร็วทันใจและประหยัดพลังงาน สำหรับงานประจำวัน",
    category: ["recommended", "fast", "chat", "google", "all"],
    capabilities: ["Fast", "Vision", "Multimodal"],
    contextWindow: "1,000,000 Tokens",
    speed: "Ultra Fast",
    isNew: true,
    isPopular: true,
    defaultTemperature: 0.7,
    maxTokens: 4096,
  },
  {
    id: "goomiru-4-pro",
    name: "Goomiru 4 (Flagship)",
    provider: "Goomiru",
    iconUrl: "/icon.svg",
    description: "เหมาะสำหรับ:โมเดลเรือธงอัจฉริยะของ Goomiru ฉลาดรอบด้าน วิเคราะห์เชิงลึก และตอบภาษาไทยอย่างเป็นธรรมชาติสูงสุด",
    category: ["recommended", "chat", "reasoning", "coding", "all"],
    capabilities: ["Reasoning", "Coding", "Fast", "Multimodal"],
    contextWindow: "256,000 Tokens",
    speed: "Ultra Fast",
    isNew: true,
    isPopular: true,
    isFeatured: true,
    defaultTemperature: 0.7,
    maxTokens: 8192,
  },
  {
    id: "gemini-3.1-pro",
    name: "Gemini 3.1 Pro (Preview)",
    provider: "Google",
    iconUrl: "https://i.redd.it/zl9bvu94ui3f1.png",
    description: "เหมาะสำหรับ:ก้าวกระโดดของความฉลาดและการใช้เหตุผลในรุ่นทดลองที่ล้ำสมัยที่สุด",
    category: ["recommended", "chat", "research", "google", "all"],
    capabilities: ["Reasoning", "Long Context", "Vision", "Multimodal"],
    contextWindow: "2,000,000 Tokens",
    speed: "Ultra Fast",
    defaultTemperature: 0.7,
    maxTokens: 8192,
  },
  {
    id: "claude-3-7-sonnet",
    name: "Claude 3.7 Sonnet (Hybrid)",
    provider: "Anthropic",
    iconUrl: "https://cdn-1.webcatalog.io/catalog/claude/claude-icon-filled-256.png?v=1785717226637",
    description: "เหมาะสำหรับ:โมเดลรุ่นท็อปล่าสุด ผสานการคิดเชิงลึกและการตอบไว เขียนโค้ดระดับโปร",
    category: ["recommended", "chat", "coding", "reasoning", "anthropic", "all"],
    capabilities: ["Reasoning", "Coding", "Vision"],
    contextWindow: "200,000 Tokens",
    speed: "Fast",
    isNew: true,
    isPopular: true,
    defaultTemperature: 0.7,
    maxTokens: 8192,
  },
  {
    id: "claude-3-5-sonnet",
    name: "Claude 3.5 Sonnet",
    provider: "Anthropic",
    iconUrl: "https://cdn-1.webcatalog.io/catalog/claude/claude-icon-filled-256.png?v=1785717226637",
    description: "เหมาะสำหรับ:มาตรฐานทองคำของการเขียนโค้ด การใช้เหตุผล และความเข้าใจภาษาขั้นสูง",
    category: ["recommended", "chat", "coding", "anthropic", "all"],
    capabilities: ["Reasoning", "Coding", "Vision"],
    contextWindow: "200,000 Tokens",
    speed: "Fast",
    defaultTemperature: 0.7,
    maxTokens: 8192,
  },
  {
    id: "claude-3-5-haiku",
    name: "Claude 3.5 Haiku",
    provider: "Anthropic",
    iconUrl: "https://cdn-1.webcatalog.io/catalog/claude/claude-icon-filled-256.png?v=1785717226637",
    description: "เหมาะสำหรับ:โมเดลขนาดกะทัดรัดที่เร็วเป็นพิเศษ ประหยัด และแม่นยำสูง",
    category: ["fast", "chat", "anthropic", "all"],
    capabilities: ["Fast", "Reasoning"],
    contextWindow: "200,000 Tokens",
    speed: "Ultra Fast",
    defaultTemperature: 0.7,
    maxTokens: 4096,
  },
  {
    id: "claude-3-opus",
    name: "Claude 3 Opus",
    provider: "Anthropic",
    iconUrl: "https://cdn-1.webcatalog.io/catalog/claude/claude-icon-filled-256.png?v=1785717226637",
    description: "เหมาะสำหรับ:งานวิเคราะห์เชิงลึกที่ซับซ้อน งานเขียนสร้างสรรค์ และการประมวลผลระดับสูง",
    category: ["research", "advanced", "anthropic", "all"],
    capabilities: ["Reasoning", "Research"],
    contextWindow: "200,000 Tokens",
    speed: "Deep Reasoning",
    defaultTemperature: 0.6,
    maxTokens: 4096,
  },
  {
    id: "claude-sonnet-5",
    name: "Claude Sonnet 5 (Next-Gen)",
    provider: "Anthropic",
    iconUrl: "https://cdn-1.webcatalog.io/catalog/claude/claude-icon-filled-256.png?v=1785717226637",
    description: "เหมาะสำหรับ:รุ่นสมดุลล่าสุดที่ฉลาดและรวดเร็ว เหมาะสำหรับงานทั่วไปและงานสร้างสรรค์",
    category: ["recommended", "chat", "coding", "anthropic", "all"],
    capabilities: ["Reasoning", "Coding", "Vision"],
    contextWindow: "200,000 Tokens",
    speed: "Fast",
    defaultTemperature: 0.7,
    maxTokens: 8192,
  },
  {
    id: "claude-opus-5",
    name: "Claude Opus 5 (Next-Gen)",
    provider: "Anthropic",
    iconUrl: "https://cdn-1.webcatalog.io/catalog/claude/claude-icon-filled-256.png?v=1785717226637",
    description: "เหมาะสำหรับ:โมเดล Opus ล่าสุดสำหรับการใช้เหตุผลขั้นสูง งานโค้ดเชิงตัวแทน และงานซับซ้อนระยะยาว",
    category: ["research", "advanced", "anthropic", "all"],
    capabilities: ["Reasoning", "Research", "Coding"],
    contextWindow: "200,000 Tokens",
    speed: "Deep Reasoning",
    isPro: true,
    defaultTemperature: 0.6,
    maxTokens: 4096,
  },
  {
    id: "gpt-5.6-terra",
    name: "GPT-5.6 Terra",
    provider: "OpenAI",
    iconUrl: "https://st5.depositphotos.com/32755884/69707/v/450/depositphotos_697076598-stock-illustration-chatgpt-sign-artificial-intelligence-chatbot.jpg",
    description: "เหมาะสำหรับ:GPT-5.6 รุ่นสมดุลระหว่างความฉลาดและความคุ้มค่า",
    category: ["chat", "openai", "all"],
    capabilities: ["Reasoning", "Fast", "Vision"],
    contextWindow: "256,000 Tokens",
    speed: "Ultra Fast",
    defaultTemperature: 0.7,
    maxTokens: 4096,
  },
  {
    id: "qwen-2-5-max",
    name: "Qwen 2.5 Max (Alibaba)",
    provider: "Qwen",
    iconUrl: "https://img.alicdn.com/imgextra/i2/O1CN01O3yvA9a9cuE0IsjU_!!6000000001451-2-tps-150-150.png_.webp",
    description: "เหมาะสำหรับ:โมเดลเรือธงจาก Alibaba ฉลาดรอบด้าน รองรับภาษาไทยและงานโค้ดขั้นสูง",
    category: ["recommended", "chat", "coding", "all"],
    capabilities: ["Fast", "Reasoning", "Coding"],
    contextWindow: "128,000 Tokens",
    speed: "Ultra Fast",
    defaultTemperature: 0.7,
    maxTokens: 4096,
  },
  {
    id: "glm-4-plus",
    name: "GLM-4 Plus (Z.ai)",
    provider: "GLM",
    iconUrl: "https://img.alicdn.com/imgextra/i2/O1CN01OoajDD267jC7ai1m2_!!6000000007615-55-tps-32-32.svg",
    description: "เหมาะสำหรับ:โมเดลตระกูล GLM ทรงพลัง ด้านการสรุปความ คิดวิเคราะห์ และการสนทนาภาษาไทย",
    category: ["recommended", "chat", "research", "all"],
    capabilities: ["Reasoning", "Long Context"],
    contextWindow: "128,000 Tokens",
    speed: "Fast",
    defaultTemperature: 0.7,
    maxTokens: 4096,
  },
  {
    id: "kimi-k1-5",
    name: "Kimi k1.5 (Moonshot)",
    provider: "Kimi",
    iconUrl: "https://img.alicdn.com/imgextra/i4/O1CN01Pjtj4a1zHcQIgevpV_!!6000000006689-55-tps-28-28.svg",
    description: "เหมาะสำหรับ:การอ่านเอกสารขนาดยาวพิเศษ การจับใจความ และการสืบค้นข้อมูลเชิงลึก",
    category: ["research", "chat", "all"],
    capabilities: ["Reasoning", "Long Context"],
    contextWindow: "200,000 Tokens",
    speed: "Fast",
    defaultTemperature: 0.6,
    maxTokens: 4096,
  },
  {
    id: "flux-1.1-pro",
    name: "Flux 1.1 Pro Ultra",
    provider: "Flux",
    iconUrl: "https://img-cdn.flux.ai/eyJidWNrZXQiOiJncmF2aXRvbi1lbGVjdHJpYy1zeW1ib2xzIiwia2V5IjoidXNlcl9hdmF0YXJzL0ZsdXgtb24tQmxhY2stY2U1MTljZGYtYzZkYy00NzQxLThiMDItMTIxZmQ3MmE1OGJiLmpwZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6MzIwLCJoZWlnaHQiOjMyMCwiZml0IjoiY292ZXIiLCJiYWNrZ3JvdW5kIjp7InIiOjAsImciOjAsImIiOjAsImFscGhhIjowfX19LCJvdXRwdXRGb3JtYXQiOiJ3ZWJwIn0=",
    description: "เหมาะสำหรับ:การเจนเนอเรตภาพความละเอียดสูงระดับโฟโต้เรียลลิสติก",
    category: ["image"],
    capabilities: ["Creative", "Vision"],
    contextWindow: "Prompt Based",
    speed: "Fast",
    defaultTemperature: 0.9,
  },
  {
    id: "sora-cinematic-v2",
    name: "Sora Cinematic v2",
    provider: "Sora",
    iconUrl: "https://youlynq.me/wp-content/uploads/2025/10/16_x_9____1_.png",
    description: "เหมาะสำหรับ:การสร้างคลิปวิดีโอภาพยนตร์ความละเอียดสูงพร้อมฟิสิกส์สมจริง",
    category: ["video"],
    capabilities: ["Creative", "Vision"],
    contextWindow: "Storyboard Based",
    speed: "Balanced",
    defaultTemperature: 0.8,
  },
  {
    id: "suno-v4-music",
    name: "Suno AI Maestro v4",
    provider: "Suno",
    iconUrl: "https://storage.inskru.com/ideas/covers/1754574921486977294.jpg",
    description: "เหมาะสำหรับ:การประพันธ์บทเพลง ทำนอง ดนตรี และเนื้อร้องระดับสตูดิโอ",
    category: ["music"],
    capabilities: ["Creative", "Audio"],
    contextWindow: "Lyric Based",
    speed: "Fast",
    defaultTemperature: 0.85,
  },
  {
    id: "deepseek-chat",
    name: "DeepSeek V3 (Chat)",
    provider: "DeepSeek",
    iconUrl: "https://www.morphcast.com/wp-content/uploads/2025/01/deepseek.jpg.webp",
    description: "เหมาะสำหรับ:โมเดลตัวเบาที่เร็วที่สุด ตอบผุดคำแบบเรียลไทม์ ประหยัดและฉลาดรอบด้าน",
    category: ["recommended", "chat", "fast", "deepseek", "all"],
    capabilities: ["Fast", "Reasoning", "Coding"],
    contextWindow: "128,000 Tokens",
    speed: "Ultra Fast",
    defaultTemperature: 0.7,
    maxTokens: 4096,
  },
  {
    id: "deepseek-r2",
    name: "DeepSeek R1 / R2 (Reasoner)",
    provider: "DeepSeek",
    iconUrl: "https://www.morphcast.com/wp-content/uploads/2025/01/deepseek.jpg.webp",
    description: "เหมาะสำหรับ:การแก้โจทย์คณิตศาสตร์และการคิดคำนวณแบบ Chain of Thought ความแม่นยำสูง",
    category: ["reasoning", "coding", "deepseek", "all"],
    capabilities: ["Reasoning", "Coding"],
    contextWindow: "128,000 Tokens",
    speed: "Deep Reasoning",
    defaultTemperature: 0.6,
    maxTokens: 8192,
  },
];

export const DEFAULT_MODEL_ID = "gemini-3.1-flash-lite";
