import { Model, ModelCategory } from "@/lib/types";

export interface CategoryTab {
  id: ModelCategory;
  label: string;
  iconName?: string;
}

export const MODEL_CATEGORIES: CategoryTab[] = [
  { id: "recommended", label: "แนะนำ", iconName: "Sparkles" },
  { id: "all", label: "ไม่จำกัด" },
  { id: "chat", label: "สนทนา", iconName: "MessageSquare" },
  { id: "research", label: "ค้นคว้าเชิงลึก", iconName: "Telescope" },
  { id: "image", label: "สร้างรูปภาพ", iconName: "Image" },
  { id: "video", label: "สร้างวิดีโอ", iconName: "Clapperboard" },
  { id: "music", label: "สร้างเพลง", iconName: "Music" },
  { id: "deepseek", label: "DeepSeek", iconName: "Sparkles" },
  { id: "google", label: "Google", iconName: "Sparkles" },
  { id: "anthropic", label: "Anthropic" },
  { id: "openai", label: "OpenAI" },
];

export const AVAILABLE_MODELS: Model[] = [
  {
    id: "deepseek-chat",
    name: "DeepSeek V3 (Chat)",
    provider: "DeepSeek",
    iconUrl: "https://www.morphcast.com/wp-content/uploads/2025/01/deepseek.jpg.webp",
    description: "เหมาะสำหรับ:โมเดลตัวเบาที่เร็วที่สุด ตอบผุดคำแบบเรียลไทม์ ประหยัดและฉลาดรอบด้าน",
    category: ["recommended", "chat", "fast", "deepseek", "all"],
    capabilities: ["Fast", "Reasoning", "Coding"],
    contextWindow: "128,000 Tokens",
    speed: "Ultra Fast",
    isNew: true,
    isPopular: true,
    defaultTemperature: 0.7,
    maxTokens: 4096,
  },
  {
    id: "deepseek-r2",
    name: "DeepSeek R1 / R2 (Reasoner)",
    provider: "DeepSeek",
    iconUrl: "https://www.morphcast.com/wp-content/uploads/2025/01/deepseek.jpg.webp",
    description: "เหมาะสำหรับ:การแก้โจทย์คณิตศาสตร์และการคิดคำนวณแบบ Chain of Thought ความแม่นยำสูง",
    category: ["reasoning", "coding", "deepseek", "all"],
    capabilities: ["Reasoning", "Coding"],
    contextWindow: "128,000 Tokens",
    speed: "Deep Reasoning",
    defaultTemperature: 0.6,
    maxTokens: 8192,
  },
  {
    id: "gemini-3.1-flash-lite",
    name: "Gemini 3.1 Flash Lite",
    provider: "Google",
    iconUrl: "https://i.redd.it/zl9bvu94ui3f1.png",
    description: "เหมาะสำหรับ:การตอบกลับที่รวดเร็วทันใจและประหยัดพลังงาน สำหรับงานประจำวัน",
    category: ["recommended", "fast", "chat", "google", "all"],
    capabilities: ["Fast", "Vision", "Multimodal"],
    contextWindow: "1,000,000 Tokens",
    speed: "Ultra Fast",
    defaultTemperature: 0.7,
    maxTokens: 4096,
  },
  {
    id: "gemini-3.1-pro",
    name: "Gemini 3.1 Pro (Preview)",
    provider: "Google",
    iconUrl: "https://i.redd.it/zl9bvu94ui3f1.png",
    description: "เหมาะสำหรับ:ก้าวกระโดดของความฉลาดและการใช้เหตุผลในรุ่นทดลองที่ล้ำสมัยที่สุด",
    category: ["recommended", "chat", "research", "google", "all"],
    capabilities: ["Reasoning", "Long Context", "Vision", "Multimodal"],
    contextWindow: "2,000,000 Tokens",
    speed: "Ultra Fast",
    isNew: true,
    defaultTemperature: 0.7,
    maxTokens: 8192,
  },
  {
    id: "claude-sonnet-5",
    name: "Claude Sonnet 5",
    provider: "Anthropic",
    iconUrl: "https://cdn-1.webcatalog.io/catalog/claude/claude-icon-filled-256.png?v=1785717226637",
    description: "เหมาะสำหรับ:รุ่นสมดุลล่าสุดที่ฉลาดและรวดเร็ว เหมาะสำหรับงานทั่วไปและงานสร้างสรรค์",
    category: ["recommended", "chat", "coding", "anthropic", "all"],
    capabilities: ["Reasoning", "Coding", "Vision"],
    contextWindow: "200,000 Tokens",
    speed: "Fast",
    defaultTemperature: 0.7,
    maxTokens: 8192,
  },
  {
    id: "claude-opus-5",
    name: "Claude Opus 5",
    provider: "Anthropic",
    iconUrl: "https://cdn-1.webcatalog.io/catalog/claude/claude-icon-filled-256.png?v=1785717226637",
    description: "เหมาะสำหรับ:โมเดล Opus ล่าสุดสำหรับการใช้เหตุผลขั้นสูง งานโค้ดเชิงตัวแทน และงานซับซ้อนระยะยาว",
    category: ["research", "advanced", "anthropic"],
    capabilities: ["Reasoning", "Research", "Coding"],
    contextWindow: "200,000 Tokens",
    speed: "Deep Reasoning",
    isPro: true,
    defaultTemperature: 0.6,
    maxTokens: 4096,
  },
  {
    id: "gpt-5.6-terra",
    name: "GPT-5.6 Terra",
    provider: "OpenAI",
    iconUrl: "https://st5.depositphotos.com/32755884/69707/v/450/depositphotos_697076598-stock-illustration-chatgpt-sign-artificial-intelligence-chatbot.jpg",
    description: "เหมาะสำหรับ:GPT-5.6 รุ่นสมดุลระหว่างความฉลาดและความคุ้มค่า",
    category: ["chat", "openai", "all"],
    capabilities: ["Reasoning", "Fast", "Vision"],
    contextWindow: "256,000 Tokens",
    speed: "Ultra Fast",
    defaultTemperature: 0.7,
    maxTokens: 4096,
  },
  {
    id: "flux-1.1-pro",
    name: "Flux 1.1 Pro Ultra",
    provider: "Flux",
    iconUrl: "https://img-cdn.flux.ai/eyJidWNrZXQiOiJncmF2aXRvbi1lbGVjdHJpYy1zeW1ib2xzIiwia2V5IjoidXNlcl9hdmF0YXJzL0ZsdXgtb24tQmxhY2stY2U1MTljZGYtYzZkYy00NzQxLThiMDItMTIxZmQ3MmE1OGJiLmpwZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6MzIwLCJoZWlnaHQiOjMyMCwiZml0IjoiY292ZXIiLCJiYWNrZ3JvdW5kIjp7InIiOjAsImciOjAsImIiOjAsImFscGhhIjowfX19LCJvdXRwdXRGb3JtYXQiOiJ3ZWJwIn0=",
    description: "เหมาะสำหรับ:การเจนเนอเรตภาพความละเอียดสูงระดับโฟโต้เรียลลิสติก",
    category: ["image"],
    capabilities: ["Creative", "Vision"],
    contextWindow: "Prompt Based",
    speed: "Fast",
    defaultTemperature: 0.9,
  },
  {
    id: "sora-cinematic-v2",
    name: "Sora Cinematic v2",
    provider: "Sora",
    iconUrl: "https://youlynq.me/wp-content/uploads/2025/10/16_x_9____1_.png",
    description: "เหมาะสำหรับ:การสร้างคลิปวิดีโอภาพยนตร์ความละเอียดสูงพร้อมฟิสิกส์สมจริง",
    category: ["video"],
    capabilities: ["Creative", "Vision"],
    contextWindow: "Storyboard Based",
    speed: "Balanced",
    defaultTemperature: 0.8,
  },
  {
    id: "suno-v4-music",
    name: "Suno AI Maestro v4",
    provider: "Suno",
    iconUrl: "https://storage.inskru.com/ideas/covers/1754574921486977294.jpg",
    description: "เหมาะสำหรับ:การประพันธ์บทเพลง ทำนอง ดนตรี และเนื้อร้องระดับสตูดิโอ",
    category: ["music"],
    capabilities: ["Creative", "Audio"],
    contextWindow: "Lyric Based",
    speed: "Fast",
    defaultTemperature: 0.85,
  },
];

export const DEFAULT_MODEL_ID = "deepseek-chat";
